### ISSUE TITLE
getting error for material dialog library.

### ISSUE THREAD

**Issue by TechnologyMaster** [crazyhitty/Rss-Manager#4]
I have already use material dialog library in my project.
compile 'com.afollestad.material-dialogs:core:0.9.1.0' 
now i use your library but gradle sync failed and shows error.
Error:Failed to resolve: com.github.afollestad.material-dialogs:core:0.8.5.6
<a href="openFile:/home/wpa1/Dharmishtha/Projects/GitProject/NewsApp/app/build.gradle">Open File</a><br>
Show in Project Structure dialog</a>

**Comment by crazyhitty** [comment]
MaterialDialogs are no longer part of the library.
